# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Research
    url: research/
    weight: 20
    share: false
  - name: Teaching
    url: uses/
    weight: 30
  - name: Awards & Grants
    url: uses/
    weight: 40
  - name: CV
    url: uses/
    weight: 50
  - name: Photos
    url: uses/
    weight: 60